CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done boolean NOT NULL,
    projectId integer REFERENCES projects(id)
);

INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make a Web App', 1, 'Using Javascript', '2019-05-12');

INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make an App', 1, 'Using Dark', '2019-05-13');

INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make a Desktop App', 1, 'Using C++', '2019-05-14');

-- Insert task data
INSERT INTO tasks (name, done, projectId)
VALUES ('Download Vuejs', false, 1);

INSERT INTO tasks (name, done, projectId)
VALUES ('Create UI Web', false, 1);

INSERT INTO tasks (name, done, projectId)
VALUES ('Download Flutter', false, 2);

INSERT INTO tasks (name, done, projectId)
VALUES ('Design UI', false, 2);



CREATE TABLE IF NOT EXISTS empresa(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    razonsocial character varying(3000),
    descripcion character varying(3000),
    telefono character varying,
    nit character varying,
    representante  character varying,
    logo bytea,
    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    estado character varying
);

CREATE TABLE IF NOT EXISTS sucursal(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre character varying(3000),
    descripcion character varying(3000),
    telefono character varying,
    actividad character varying,
    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    estado character varying,
     empresaId integer REFERENCES empresa(id)
);

-- CREATE TABLE IF NOT EXISTS usuario(
--     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     nombrecompleto character varying(3000),
--     usuario character varying(3000),
--     password character varying,
--     usuarioregistro character varying,
--     usuariomodificacion character varying,
--     fecharegistro timestamp,
--     fechamodificacion timestamp,
--     estado character varying
-- );

CREATE TABLE IF NOT EXISTS usuario(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombrecompleto character varying,
    nick character varying,
    password character varying,
    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    estado character varying
);

CREATE TABLE IF NOT EXISTS perfil(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre character varying,
    descripcion character varying(300),
    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    estado character varying,
     sucursalId integer REFERENCES sucursal(id)
);

CREATE TABLE IF NOT EXISTS usuario_perfil(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     usuarioId integer REFERENCES usuario(id),
      perfilId integer REFERENCES perfil(id),
    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    estado character varying,
);

CREATE TABLE IF NOT EXISTS sucursal_usuario(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     usuarioId integer REFERENCES usuario(id),
      sucursalId integer REFERENCES sucursal(id),
    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    estado character varying
);

CREATE TABLE IF NOT EXISTS pagina(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre character varying,
    descripcion character varying(300),
     url character varying(300),
    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    tipo character varying,
    paginaId integer REFERENCES pagina(id),
    estado character varying
);


CREATE TABLE IF NOT EXISTS accion(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre character varying,
    descripcion character varying(300),
    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    estado character varying
);

CREATE TABLE IF NOT EXISTS permiso(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     accionId integer REFERENCES accion(id),
      paginaId integer REFERENCES pagina(id),
        perfilId integer REFERENCES perfil(id),
    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    estado character varying
);