CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done boolean NOT NULL,
    projectId integer REFERENCES projects(id)
);

INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make a Web App', 1, 'Using Javascript', '2019-05-12');

INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make an App', 1, 'Using Dark', '2019-05-13');

INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make a Desktop App', 1, 'Using C++', '2019-05-14');

-- Insert task data
INSERT INTO tasks (name, done, projectId)
VALUES ('Download Vuejs', false, 1);

INSERT INTO tasks (name, done, projectId)
VALUES ('Create UI Web', false, 1);

INSERT INTO tasks (name, done, projectId)
VALUES ('Download Flutter', false, 2);

INSERT INTO tasks (name, done, projectId)
VALUES ('Design UI', false, 2);



CREATE TABLE IF NOT EXISTS empresa(
    --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    razonsocial character varying(3000),
    descripcion character varying(3000),
    telefono character varying,
    nit character varying,
    representante  character varying,
    logo bytea,
    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    estado character varying
);

CREATE TABLE IF NOT EXISTS sucursal(
     --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    nombre character varying(3000)  not null,
    descripcion character varying(3000),
    telefono character varying,
    actividad character varying,
    representante character varying,
    direccion character varying,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
     empresaId character varying REFERENCES empresa(id),     
     departamentoid character varying REFERENCES departamento(id)
);

-- CREATE TABLE IF NOT EXISTS usuario(
--     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     nombrecompleto character varying(3000),
--     usuario character varying(3000),
--     password character varying,
--     usuarioregistro character varying,
--     usuariomodificacion character varying,
--     fecharegistro timestamp,
--     fechamodificacion timestamp,
--     estado character varying
-- );

CREATE TABLE IF NOT EXISTS usuario(
     --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    --nombrecompleto character varying,
    nick character varying  not null unique,
    password character varying  not null,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    empresaid character varying REFERENCES empresa(id),
    personalid character varying REFERENCES personal(id),
    estado character varying  not null
);

CREATE TABLE IF NOT EXISTS departamento(
    --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    nombre character varying,
    descripcion character varying(300),
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
     --sucursalId integer REFERENCES sucursal(id)
     empresaId character varying REFERENCES empresa(id)
);

insert into departamento(nombre,descripcion,usuarioregistro,fecharegistro,fechamodificacion,estado,empresaid)
values('Santa Cruz','Santa Cruz','admin',Now(),now(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e'),
('Cochabamba','Cochabamba','admin',Now(),now(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e'),
('La Paz','La Paz','admin',Now(),now(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e'),
('Oruro','Oruro','admin',Now(),now(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e'),
('Beni','Beni','admin',Now(),now(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e'),
('Pando','Pando','admin',Now(),now(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e'),
('Chuquisaca','Chuquisaca','admin',Now(),now(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e'),
('Tarija','Tarija','admin',Now(),now(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e'),
('Potosi','Potosi','admin',Now(),now(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e')


CREATE TABLE IF NOT EXISTS perfil(
    --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    nombre character varying,
    descripcion character varying(300),
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
     sucursalid integer REFERENCES sucursal(id),
     empresaId character varying REFERENCES empresa(id)
);

CREATE TABLE IF NOT EXISTS usuario_perfil(
    --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
     usuarioId character varying REFERENCES usuario(id),
      perfilId character varying REFERENCES perfil(id),
    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null
);

CREATE TABLE IF NOT EXISTS sucursal_usuario(
    --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
     usuarioid character varying REFERENCES usuario(id),
      sucursalid character varying REFERENCES sucursal(id),
    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    estado character varying  not null
);

CREATE TABLE IF NOT EXISTS pagina(
    --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    nombre character varying  not null,
    descripcion character varying(300),
     url character varying(300),
     icon character varying,
     badgeStyleClass character varying,
     badge character varying,
     orden integer,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    tipo character varying,
    paginaId character varying REFERENCES pagina(id),
    estado character varying  not null
);


insert into pagina(nombre,descripcion,url,usuarioregistro,fecharegistro,tipo,estado)
values ('CARTERA','CARTERA','/cartera','dticlla',NOW(),'MODULO','ACT')


insert into pagina(nombre,descripcion,url,usuarioregistro,fecharegistro,tipo,estado,paginaId)
values ('registro asegurado','registro asegurado','/registroAsegurado','dticlla',now(),'PAGINA','ACT','ecac13bc-7b55-4571-9c63-29986d92a681')


CREATE TABLE IF NOT EXISTS accion(
     --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    nombre character varying  not null,
    descripcion character varying(300),
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying not null
    --,
     --paginaid character varying REFERENCES pagina(id)
);



insert into accion(nombre,descripcion,usuarioregistro,fecharegistro,estado,paginaId)
values ('REGISTRAR','REGISTRAR','DTICLLA',NOW(),'ACT','483248aa-71b5-45a0-a00b-a0642c176951'),
('MODIFICAR','MODIFICAR','DTICLLA',NOW(),'ACT','483248aa-71b5-45a0-a00b-a0642c176951'),
('LISTAR','LISTAR','DTICLLA',NOW(),'ACT','483248aa-71b5-45a0-a00b-a0642c176951'),
('APROBAR','APROBAR','DTICLLA',NOW(),'ACT','483248aa-71b5-45a0-a00b-a0642c176951'),
('BAJA','BAJA','DTICLLA',NOW(),'ACT','483248aa-71b5-45a0-a00b-a0642c176951');


CREATE TABLE IF NOT EXISTS pagina_accion(
     id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying not null,
     paginaid character varying REFERENCES pagina(id),
     accionid character varying REFERENCES accion(id)
);

/* insert into pagina_accion(paginaid,accionid,usuarioregistro,fecharegistro,estado)
values (2,1,'DTICLLA',NOW(),'ACT'),
(2,2,'DTICLLA',NOW(),'ACT'),
(2,3,'DTICLLA',NOW(),'ACT'),
(2,4,'DTICLLA',NOW(),'ACT'),
(2,5,'DTICLLA',NOW(),'ACT')
 */
CREATE TABLE IF NOT EXISTS permiso(
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
     --accionid character varying REFERENCES accion(id) ,
      --paginaid character varying REFERENCES pagina(id),
	paginaaccionid character varying REFERENCES pagina_accion(id),
        perfilid character varying REFERENCES perfil(id),
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null
);



---SISTEMA PATRIA

CREATE TABLE IF NOT EXISTS area_trabajo(
     --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
     nombre character varying not null ,
      descripcion character varying ,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
     empresaid character varying REFERENCES empresa(id)
);


CREATE TABLE IF NOT EXISTS personal(
     --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    nombrecompleto character varying not null ,
    sexo character varying not null  ,
    fechanacimiento date not null ,
    ci character varying not null ,
    telefono1 character varying,
    telefono2 character varying,
    correo1 character varying,
    correo2 character varying,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
    areatrabajoid character varying REFERENCES area_trabajo(id),
    sucursalid character varying REFERENCES sucursal(id)
);


/* insert into pagina_accion(usuarioregistro,fecharegistro,fechamodificacion,estado,paginaid,accionid)
select 'DTICLLA',now(),now(),'ACT','8a458081-96c1-4311-a4a0-115573bd44e8',id from  accion order by nombre

insert into pagina_accion(usuarioregistro,fecharegistro,fechamodificacion,estado,paginaid,accionid)
select 'DTICLLA',now(),now(),'ACT','67032632-01dc-4300-a3df-1414e90c3b77',id from  accion order by nombre

insert into pagina_accion(usuarioregistro,fecharegistro,fechamodificacion,estado,paginaid,accionid)
select 'DTICLLA',now(),now(),'ACT','4fad64b6-db35-4d21-a172-763ae158922c',id from  accion order by nombre

insert into pagina_accion(usuarioregistro,fecharegistro,fechamodificacion,estado,paginaid,accionid)
select 'DTICLLA',now(),now(),'ACT','b3341b14-5b50-4d92-ac4f-25f687a80d88',id from  accion order by nombre

insert into pagina_accion(usuarioregistro,fecharegistro,fechamodificacion,estado,paginaid,accionid)
select 'DTICLLA',now(),now(),'ACT','2658bfcd-76c2-4aa5-9bde-11d5cc12480f',id from  accion order by nombre

insert into pagina_accion(usuarioregistro,fecharegistro,fechamodificacion,estado,paginaid,accionid)
select 'DTICLLA',now(),now(),'ACT','5adfc0c3-5f38-4119-a667-d2dca57cfdb3',id from  accion order by nombre */



CREATE TABLE IF NOT EXISTS asegurado(
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    tipoasegurado character varying not null,
    apellidopaterno character varying,
    apellidomaterno character varying,
    nombres character varying not null,
    nombrecompleto character varying not null,
    ci character varying ,
    nit character varying ,
    sexo character varying ,
    telefonoasegurado character varying ,
    telefonodomicilio character varying ,
    telefonotrabajo character varying ,
    correo character varying ,
    fotografia bytea,
    direccionasegurado character varying ,
    fechanacimiento timestamp null,

      fechavencimientocarnet timestamp default null,
    fechavencimientobrevet timestamp default null,
    fechavencimientofundempresa timestamp default null,
    relacionasegurado character varying ,
    cargorepresentante character varying,

    apellidopaternocobranza character varying ,
    apellidomaternocobranza character varying ,
    nombrescobranza character varying ,
    nombrecompletocobranza character varying ,
    telefonocobranza character varying ,
    direccioncobranza character varying ,

    apellidopaternorepresentante character varying ,
    apellidomaternorepresentante character varying ,
    nombresrepresentante character varying ,
    nombrecompletorepresentante character varying ,
    direccionrepresentante character varying ,
    emailrepresentante character varying ,
    telefonorepresentante character varying ,
    celularrepresentante character varying ,
    
    usuarioregistro character varying  not null,
    usuariobaja character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    fechabaja timestamp,
    estado character varying  not null,
     departamentoid character varying REFERENCES departamento(id),
    sucursalid character varying REFERENCES sucursal(id),
    ejecutivoid character varying REFERENCES personal(id),
    carteraid character varying REFERENCES personal(id)
);


CREATE TABLE IF NOT EXISTS compania_seguro(
     --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    nombre character varying not null ,
    descripcion character varying ,
    nit character varying not null,
    representante_legal character varying ,
    direccion character varying not null,
    telefono1 character varying,
    telefono2 character varying,
    web character varying,
    cia_spvs character varying,
    nrocuenta character varying,
    banco1 character varying,
    tipomoneda1 character varying,
    nrocuenta2 character varying,
    banco2 character varying,
    tipomoneda2 character varying,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
     empresaid character varying REFERENCES empresa(id)
);



insert into compania_seguro(nombre , descripcion,direccion,telefono1,cia_spvs,estado,fecharegistro,nit,usuarioregistro)
values ('ALIANZA COMPAÑÍA DE SEGUROS Y REASEGUROS S.A.',null,'Av. Roca y Coronado Esq. 3er. Anillo Externo','363-2727','108','ACT',NOW(),'---','dticlla'),
('ALIANZA VIDA DE SEGUROS Y REASEGUROS S.A.',null,'Monseñor Rivero',null,'207','ACT',NOW(),'---','dticlla'),
('LA BOLIVIANA CIACRUZ SEGUROS PERSONALES S.A.',null,'5to anillo',null,'204','ACT',NOW(),'---','dticlla'),
('BISA SEGUROS Y REASEGUROS S.A.',null,'AV. Las Americas',null,'109','ACT',NOW(),'---','dticlla'),
('CREDINFORM INTERNATIONAL S.A.',null,'null',null,'102','ACT',NOW(),'---','dticlla'),
('NACIONAL SEGUROS PATRIMONIALES Y FIANZAS S.A.',null,'null',null,'115','ACT',NOW(),'---','dticlla'),
('LA BOLIVIANA CIACRUZ DE SEGUROS Y REASEGUROS S.A.',null,'null',null,'101','ACT',NOW(),'---','dticlla'),
('LA VITALICIA SEGUROS Y REASEGUROS DE VIDA S.A.',null,'null',null,'203','ACT',NOW(),'---','dticlla'),
('FORTALEZA SEGUROS Y REASEGUROS S.A.',null,'null',null,'113','ACT',NOW(),'---','dticlla'),
('NACIONAL VIDA SEGUROS DE PERSONAS S.A.',null,'null',null,'206','ACT',NOW(),'---','dticlla'),
('SEGUROS ILLIMANI S.A',null,'null',null,'105','ACT',NOW(),'---','dticlla'),
('BUPA INSURANCE BOLIVIA S.A.',null,'null',null,'201','ACT',NOW(),'---','dticlla'),
('APS',null,'null',null,'000','ACT',NOW(),'---','dticlla'),
('UIF',null,'null',null,'000','ACT',NOW(),'---','dticlla'),
('AFP',null,'null',null,'000','ACT',NOW(),'---','dticlla'),
('CSBP',null,'null',null,'000','ACT',NOW(),'---','dticlla'),
('SEGUROS Y REASEGUROS PERSONALES UNIVIDA S.A.',null,'null',null,'210','ACT',NOW(),'---','dticlla'),
('UNIBIENES SEGUROS Y REASEGUROS PATRIMONIALES S.A.',null,'null',null,'116','ACT',NOW(),'---','dticlla'),
('COMPAÑÍA DE SEGUROS DE VIDA FORTALEZA S.A.',null,'null',null,'211','ACT',NOW(),'---','dticlla')

CREATE TABLE IF NOT EXISTS banco(
     --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
     nombre character varying not null ,
      descripcion character varying ,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
     empresaid character varying REFERENCES empresa(id)
);


CREATE TABLE IF NOT EXISTS tipo_ramo(
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
     nombre character varying not null ,
      descripcion character varying ,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  ,
     empresaid character varying REFERENCES empresa(id)
);
insert into tipo_ramo(nombre,descripcion,usuarioregistro,fecharegistro,fechamodificacion,estado,empresaid)
values('TIPO 1','TIPO 1','DTICLLA',NOW(),NOW(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e'),
('TIPO 2','TIPO 2','DTICLLA',NOW(),NOW(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e'),
('TIPO 3','TIPO 3','DTICLLA',NOW(),NOW(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e'),
('TIPO 4','TIPO 4','DTICLLA',NOW(),NOW(),'ACT','fd2169be-1d80-4416-a009-a07658f1678e')


CREATE TABLE IF NOT EXISTS ramo(
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
     nombre character varying not null ,
      descripcion character varying ,
    spvs character varying,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
    tiporamoid character varying REFERENCES tipo_ramo(id)
   ,
    --companiaseguroid character varying REFERENCES compania_seguro(id),
     empresaid character varying REFERENCES empresa(id)
);

CREATE TABLE IF NOT EXISTS sub_ramo(
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    nombre character varying not null ,
    descripcion character varying ,
    spvs character varying,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
     ramoid character varying REFERENCES ramo(id)
);


CREATE TABLE IF NOT EXISTS sub_ramo_compania(
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    porcentajecomision decimal,
    porcentajecomisioncredito decimal,
    porcentajeprima decimal,
    porcentajeprimacredito decimal,
    nota character varying,
    notacredito character varying,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
    ramoid character varying REFERENCES ramo(id),
    subramoid character varying REFERENCES sub_ramo(id),
    companiaseguroid character varying REFERENCES compania_seguro(id)
);


/* CREATE TABLE IF NOT EXISTS tipo_poliza(
     --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
     nombre character varying not null ,
      descripcion character varying ,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
     empresaid character varying REFERENCES empresa(id)
); */

CREATE TABLE IF NOT EXISTS poliza(
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    nropoliza character varying,
    nrocertificado character varying,
    fechainicio timestamp,
    fechafin timestamp,
    fechaexpedicion timestamp,
    fechaerecepcion timestamp,
    tipomoneda character varying,
    primatotal  decimal,
    formapago character varying,
    encargadoid character varying  REFERENCES personal(id),
    bancoid character varying  REFERENCES banco(id),
    ciudadexpedicion character varying,
    broker character varying,
    notas character varying,
    companiaseguroid character varying  REFERENCES compania_seguro(id),
    subramocompaniaid character varying  REFERENCES sub_ramo_compania(id),
	tiporamoid character varying  REFERENCES tipo_ramo(id),
    contratanteid character varying  REFERENCES contratante(id),
    aseguradoid character varying  REFERENCES asegurado(id),
    ejecutivoid character varying  REFERENCES personal(id),
    colocacionid character varying,
    ciaspvs character varying,
    tipopolizaid character varying ,
    tpoliza character varying,
    tipocontrato character varying,
    memoid character varying,
    llamadoid character varying,
    vendedorid character varying,
    nroplaca character varying,
    tipoemision character varying,

    --detalle poliza
    --fechainiciovigencia timestamp,
    --fechafinvigencia timestamp,
    --fechainclusion timestamp,
    --prima  decimal,
    --porcentajeprima  decimal,
    --primaneta  decimal,
    --porcentajecomision  decimal,
    --detalle character varying,

    placa  character varying,
    tipovehiculo  character varying,
    marca  character varying,
    anio  character varying,
    color  character varying,

    usuarioregistro character varying,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
     estado   character varying not null,
     sucursalid  character varying REFERENCES sucursal(id)
);


CREATE TABLE IF NOT EXISTS poliza_detalle(
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    nropoliza character varying,
    nrocertificado character varying,
  

    --detalle poliza
    fechainiciovigencia timestamp,
    fechafinvigencia timestamp,
    fechainclusion timestamp,
    prima  decimal,
    porcentajeprima  decimal,
    primaneta  decimal,
    porcentajecomision  decimal,
    detalle character varying,

    

    usuarioregistro character varying not null,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    estado   character varying not null,
    polizaid  character varying REFERENCES poliza(id)
    --,
    --sucursalid  character varying REFERENCES sucursal(id)
);


CREATE TABLE IF NOT EXISTS poliza_adicional(
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    valor character varying,   
    dato character varying,    

    usuarioregistro character varying not null,
    usuariomodificacion character varying,
    fecharegistro timestamp,
    fechamodificacion timestamp,
    estado   character varying not null,
    polizaid  character varying REFERENCES poliza(id)
    --,
    --sucursalid  character varying REFERENCES sucursal(id)
);

CREATE TABLE IF NOT EXISTS carpeta(
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    nombre character varying not null ,
    descripcion character varying ,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  ,
     sucursalid character varying REFERENCES sucursal(id),
     carpetaid character varying REFERENCES carpeta(id)
);

CREATE TABLE IF NOT EXISTS archivo(
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),  
    nombre character varying,
    descripcion character varying,
    extension character varying,
    archivo bytea,
    tipo character varying,
    codigo character varying,

    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
    sucursalid character varying REFERENCES sucursal(id),
    aseguradoid character varying REFERENCES asegurado(id),
    carpetaid character varying REFERENCES carpeta(id)
);


CREATE TABLE IF NOT EXISTS contratante(
     --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
    nombre character varying not null ,
    nit character varying ,
    ejecutivoencargado character varying ,
    direccion character varying ,
    telefono character varying ,
    telefonoejecutivo character varying ,
    correoejecutivo character varying ,
    porcentajecomison decimal,
    porcentajecomison2 decimal,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
     sucursalid character varying REFERENCES sucursal(id)
);


CREATE TABLE IF NOT EXISTS vendedor(
     --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
     nombre character varying not null ,
      comisionvendedor decimal ,
      comisionvendedor2 decimal ,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
    sucursalid character varying REFERENCES sucursal(id),
    departamentoid character varying REFERENCES departamento(id),
     contratranteid character varying REFERENCES contratante(id)
);

CREATE TABLE IF NOT EXISTS tipo_memo(
     --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
     nombre character varying not null ,
      descripcion character varying ,
    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null,
     empresaid character varying REFERENCES empresa(id)
);

CREATE TABLE IF NOT EXISTS memo(
     --id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id character varying PRIMARY KEY  DEFAULT  gen_random_uuid(),
     memoid character varying    REFERENCES memo(id) ,
    tipomemoid: Sequelize.STRING,
    fechamemo timestamp,
    tipomoneda character varying,
    tipocambiodolares decimal,
    polizaid character varying,
    nropoliza character varying,
    nrocertificado character varying,
    fechavigenciainicial timestamp,
    fechavigenciafinal timestamp,
    fechapago timestamp,
    formapago character varying,
    primatotal decimal,
    primaneta decimal,
    montocomision decimal,
    porcentajeprima decimal,
    porcentajecomision decimal,
    primatotalbolivianos decimal,
    primanetabolivianos decimal,
    montocomisionbolivianos decimal,    
    descripcion character varying,
    tipocomision character varying,
    aseguradoid character varying    REFERENCES asegurado(id) ,
    companiaseguroid character varying,
    ciaspvs character varying,
    tiporamoid character varying    REFERENCES tipo_ramo(id) ,
    ramoid character varying    REFERENCES ramo(id) ,
    ramospvs character varying,
    subramoid character varying    REFERENCES sub_ramo(id) ,
    subramospvs character varying,
    spvs character varying,
    contratanteid character varying REFERENCES contratante(id) ,
    ejecutivoid character varying    REFERENCES personal(id) ,
    sucursalid character varying    REFERENCES sucursal(id) ,
    ciudadorigen character varying,
    cuotainicial decimal,
    nrocuotas decimal,
    cantidadcuotas decimal,
    periodopago character varying,
    impuesto character varying,
    fechaspago timestamp,
    fechaemision timestamp,
    fechaproduccion timestamp,
    mesproduccion character varying,
    tipocontrato character varying,
    cuotainicialliteral character varying,
    anioproduccion character varying,
    vendedorid character varying,
    comisionvendedor decimal,
    comisioncontratante decimal,
    depositoinicial decimal,
    montocomisionvendedor decimal,
    montocomisioncontratante decimal,
    comisionvendedor decimal,
    nombresobrogacion character varying,
    agente character varying,
    porcentajeagente decimal,
    saldocomisionbroker decimal,
    comisionvendedor decimal,
    carteraid character varying   REFERENCES personal(id),
    nroplaca character varying,

    usuarioregistro character varying  not null,
    usuariomodificacion character varying,
    fecharegistro timestamp  not null,
    fechamodificacion timestamp,
    estado character varying  not null
);

